# This CI configuration is broken into two workflows
#
# build-and-test: Workflow jobs are triggered on PR's into the master branch
# Uses 'nx affected' to lint, test & build any app or lib that has been affected
# bt the PR
#
# release-and-deploy: Workflow jobs only run when commit to master has been added
# (a PR has been merged). This workflow with lint, test & build the affected apps
# between the last commit to master. It will then run 'semantic release' to create
# a new semver GitHub release based on the commit message. If either the
# 'demo-web-functions' app (demo site hosted on Firebase) or the 'server-lambda'
# app (API server hosted on AWS Lambda) are affected by the release they will be built
# and automatically deployed.
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  serverless-framework: circleci/serverless-framework@1.0.1

setup: &setup
  working_directory: ~/ztp
  docker:
    - image: circleci/node:12

deps-restore: &deps-restore
  restore_cache:
    key: zero-to-production-{{ checksum "package-lock.json" }}

deps-cache: &deps-cache
  save_cache:
    key: zero-to-production-{{ checksum "package-lock.json" }}
    paths:
      - ./node_modules

master-only: &master-only
  filters:
    branches:
      only: master

ignore-master: &ignore-master
  filters:
    branches:
      ignore: master

ignore-develop: &ignore-develop
  filters:
    branches:
      ignore: develop

develop-only: &develop-only
  filters:
    branches:
      only: develop

jobs:
  checkout-and-install:
    <<: *setup
    steps:
      - checkout
      - <<: *deps-restore
      - run: npm install --no-save --silent
      - <<: *deps-cache

  build-and-test:
    description: Uses nx affected to lint, test & build effected project between the base and head
    parameters:
      base:
        description: The base commit for affected command
        default: origin/master
        type: string
      head:
        description: The head commit for affected command
        default: HEAD
        type: string
    <<: *setup
    steps:
      - checkout
      - <<: *deps-restore
      - run:
          name: Testing Affected Packages
          command: npx nx affected --target=test --base=<< parameters.base >> --head=<< parameters.head >>
      - run:
          name: Linting Affected Packages
          command: npx nx affected --target=lint --base=<< parameters.base >> --head=<< parameters.head >>
      - run:
          name: Building Affected Applications
          command: npx nx affected --target=build --base=<< parameters.base >> --head=<< parameters.head >> --parallel=false --configuration=ci

  build-and-test-latest:
    <<: *setup
    steps:
      - checkout
      - <<: *deps-restore
      - run:
          name: Testing Affected Packages
          command: |-
            TAG=$(git tag --sort=-committerdate --list 'v[0-9]*' | head -1);
            COMMIT=$(git rev-parse ${TAG});
            npx nx affected --target=test --base=${COMMIT} --head=origin/master
      - run:
          name: Linting Affected Packages
          command: |-
            TAG=$(git tag --sort=-committerdate --list 'v[0-9]*' | head -1);
            COMMIT=$(git rev-parse ${TAG});
            npx nx affected --target=lint --base=${COMMIT} --head=origin/master
      - run:
          name: Building Affected Applications
          command: |-
            TAG=$(git tag --sort=-committerdate --list 'v[0-9]*' | head -1);
            COMMIT=$(git rev-parse ${TAG});
            npx nx affected --target=build --base=${COMMIT} --head=origin/master --parallel=false --configuration=ci

  # Run semantic release to create a new semver release and publish to github
  release:
    <<: *setup
    steps:
      - checkout
      - <<: *deps-restore
      - run:
          name: Release
          command: npm run semantic-release || true

  # Check if the 'server-lambda' project was affected since last release
  server-lambda-deploy:
    <<: *setup
    steps:
      - checkout
      - <<: *deps-restore
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Deploy the API to AWS lambda
          command: |-
            TAG=$(git tag --sort=-committerdate --list 'v[0-9]*' | head -1);
            COMMIT=$(git rev-parse ${TAG})
            AFFECTED=$(npx nx affected:apps --plain --base=${COMMIT} --head=master);
            if [[ ${AFFECTED} == *"server-lambda"* ]]
            then
              echo "Server Lambda affected. Deploying new version";
              npx ng run server-lambda:build:production,ci;
              npx nx run server-lambda:serverless-deploy:ci;
            else
              echo "Server Lambda was not affected";
            fi

  # Check if the 'demo-web-functions' project was affected since last release
  demo-web-functions-deploy:
    <<: *setup
    steps:
      - checkout
      - <<: *deps-restore
      - run:
          name: Deploy the demo site to Firebase Functions
          command: |-
            TAG=$(git tag --sort=-committerdate --list 'v[0-9]*' | head -1);
            COMMIT=$(git rev-parse ${TAG})
            AFFECTED=$(npx nx affected:apps --plain --base=${COMMIT} --head=master);
            if [[ ${AFFECTED} == *"demo-web-functions"* ]]
            then
              echo "Demo Web Functions affected. Deploying new version";
              npx nx run demo-web-functions:build:production;
              npx nx run demo-web-functions:deploy-ci --args="--token=${FIREBASE_TOKEN}";
            else
              echo "Demo Web Functions was not affected";
            fi

workflows:
  version: 2
  develop:
    jobs:
      - checkout-and-install:
          filters:
            branches:
              ignore:
                - master
                - develop
      - build-and-test:
          filters:
            branches:
              ignore:
                - master
                - develop
          base: origin/develop
          head: HEAD
          requires:
            - checkout-and-install
  build-latest:
    jobs:
      - checkout-and-install:
          <<: *develop-only
      - build-and-test:
          <<: *develop-only
          base: origin/master
          head: HEAD
          requires:
            - checkout-and-install
  release-and-deploy:
    jobs:
      - checkout-and-install:
          <<: *master-only
      - build-and-test-latest:
          <<: *master-only
          requires:
            - checkout-and-install
      - server-lambda-deploy:
          context: aws
          <<: *master-only
          requires:
            - build-and-test-latest
      - demo-web-functions-deploy:
          <<: *master-only
          requires:
            - build-and-test-latest
      - release:
          <<: *master-only
          requires:
            - demo-web-functions-deploy
            - server-lambda-deploy
