# The build file is generic and requires Substitution to build correctly and will
# Error if not set.
# $_IMAGE_NAME : The name of the image once build
# $_PROJECT_DIRECTORY: The directory of src file
#
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
#
steps:
  # Build the container
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$_PROJECT_NAME
      - -f
      - docker/server.Dockerfile
      - --build-arg
      - PROJECT_DIRECTORY=$_PROJECT_DIRECTORY
      - .
    timeout: 500s
images:
  - gcr.io/$PROJECT_ID/$_PROJECT_NAME
